# Generated by Django 5.0.7 on 2025-11-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_emailhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailHistory',
        ),
    ]
