# Generated by Django 5.0.7 on 2025-11-14 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_delete_emailhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_client_id', models.CharField(blank=True, max_length=500)),
                ('google_client_secret', models.CharField(blank=True, max_length=500)),
                ('google_refresh_token', models.TextField(blank=True, help_text='OAuth refresh token')),
                ('gmail_address', models.EmailField(blank=True, help_text='Gmail address for sending emails', max_length=254)),
                ('calendar_id', models.CharField(blank=True, default='primary', help_text='Google Calendar ID', max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Settings',
                'verbose_name_plural': 'Google Calendar Settings',
            },
        ),
    ]
