# Generated by Django 5.0.7 on 2025-11-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_googlecalendarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=500)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google OAuth App Config',
                'verbose_name_plural': 'Google OAuth App Config',
            },
        ),
    ]
